language: node_js
node_js:
  - 12.14.1

cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token
  local_dir: build
  on:
    branch: master

script:
  - npm run build